"""adjusted Prospects to People and added extra fields

Revision ID: 0d9ce1becaa2
Revises: ff9d442e6672
Create Date: 2018-11-01 19:32:09.770562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9ce1becaa2'
down_revision = 'ff9d442e6672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('phone_cell', sa.Integer(), nullable=True),
    sa.Column('ptype', sa.String(length=6), nullable=True),
    sa.Column('pstatus', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.Column('user_account_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_account_pk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prospects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_cell', sa.INTEGER(), nullable=True),
    sa.Column('user_account_pk', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_account_pk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
