"""added ClosedDeals table, also added price for people

Revision ID: 0ea39d24f043
Revises: 0eaf05895801
Create Date: 2019-01-24 17:33:30.371560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea39d24f043'
down_revision = '0eaf05895801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('phone_cell', sa.Integer(), nullable=True),
    sa.Column('house_number', sa.String(length=140), nullable=True),
    sa.Column('street_name', sa.String(length=140), nullable=True),
    sa.Column('city_name', sa.String(length=140), nullable=True),
    sa.Column('state_name', sa.String(length=140), nullable=True),
    sa.Column('zip_code', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('user_account_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_account_pk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('people', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'price')
    op.drop_table('closed_deals')
    # ### end Alembic commands ###
