"""added addresses

Revision ID: 0eaf05895801
Revises: fa6d0cc446f6
Create Date: 2019-01-23 19:08:11.854908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eaf05895801'
down_revision = 'fa6d0cc446f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('city_name', sa.String(length=140), nullable=True))
    op.add_column('people', sa.Column('house_number', sa.String(length=140), nullable=True))
    op.add_column('people', sa.Column('state_name', sa.String(length=140), nullable=True))
    op.add_column('people', sa.Column('street_name', sa.String(length=140), nullable=True))
    op.add_column('people', sa.Column('zip_code', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'zip_code')
    op.drop_column('people', 'street_name')
    op.drop_column('people', 'state_name')
    op.drop_column('people', 'house_number')
    op.drop_column('people', 'city_name')
    # ### end Alembic commands ###
