"""added profilenotes table, cleaned up user table

Revision ID: 13cfdd30826a
Revises: 9a006c17d3a4
Create Date: 2018-11-06 19:08:24.657693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cfdd30826a'
down_revision = '9a006c17d3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnotes', sa.String(length=280), nullable=True),
    sa.Column('people_account_pk', sa.Integer(), nullable=True),
    sa.Column('user_account_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_account_pk'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_account_pk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('people', sa.Column('pnotes', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'pnotes')
    op.drop_table('profile_notes')
    # ### end Alembic commands ###
