"""added type of transaction to ClosedDeals

Revision ID: 6ab2bf6d2d26
Revises: 0ea39d24f043
Create Date: 2019-01-24 17:39:53.205020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab2bf6d2d26'
down_revision = '0ea39d24f043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('closed_deals', sa.Column('ptype', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('closed_deals', 'ptype')
    # ### end Alembic commands ###
