"""removed clients table

Revision ID: 9a006c17d3a4
Revises: 0d9ce1becaa2
Create Date: 2018-11-03 01:02:21.896604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a006c17d3a4'
down_revision = '0d9ce1becaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_cell', sa.INTEGER(), nullable=True),
    sa.Column('user_account_pk', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_account_pk'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
