"""cleaned up People table a bit

Revision ID: c5023c3ae761
Revises: 13cfdd30826a
Create Date: 2018-11-06 19:09:28.750022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5023c3ae761'
down_revision = '13cfdd30826a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'pnotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('pnotes', sa.VARCHAR(length=280), nullable=True))
    # ### end Alembic commands ###
