"""initializing db

Revision ID: fa6d0cc446f6
Revises: 
Create Date: 2018-11-08 20:48:06.309125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6d0cc446f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('phone_cell', sa.Integer(), nullable=True),
    sa.Column('ptype', sa.String(length=6), nullable=True),
    sa.Column('pstatus', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.Column('user_account_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_account_pk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnotes', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('people_account_pk', sa.Integer(), nullable=True),
    sa.Column('user_account_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_account_pk'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_account_pk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_notes_timestamp'), 'profile_notes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_notes_timestamp'), table_name='profile_notes')
    op.drop_table('profile_notes')
    op.drop_table('people')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
