"""new fields in client and prospect model

Revision ID: ff9d442e6672
Revises: 5383627baf9b
Create Date: 2018-10-27 19:11:24.364397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9d442e6672'
down_revision = '5383627baf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('notes', sa.String(length=140), nullable=True))
    op.add_column('prospects', sa.Column('notes', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'notes')
    op.drop_column('clients', 'notes')
    # ### end Alembic commands ###
